
# **Binning, Binarization and Discretization — Essential Codes**

These techniques are used in feature engineering to transform numerical data into more useful forms.

- **Binning** → Convert continuous values into intervals (bins)
- **Binarization** → Convert values into binary (0 or 1)
- **Discretization** → Convert continuous variables into categorical groups


## **1. Import Required Libraries**

In [1]:

import numpy as np
import pandas as pd

from sklearn.preprocessing import Binarizer
from sklearn.preprocessing import KBinsDiscretizer


## **2. Create Sample Dataset**

In [2]:

data = pd.DataFrame({
    "age":[18,22,25,30,35,40,45,50,55,60],
    "income":[20000,25000,30000,40000,50000,60000,70000,80000,90000,100000]
})

data

   age  income
0   18   20000
1   22   25000
2   25   30000
3   30   40000
4   35   50000
5   40   60000
6   45   70000
7   50   80000
8   55   90000
9   60  100000


# **Binning**
Binning divides continuous data into **interval groups**.

Example:

0–20 → Young  
20–40 → Adult  
40–60 → Senior


## **3. Equal Width Binning using pandas**

In [3]:

bins = [0,20,40,60]

labels = ["Young","Adult","Senior"]

data["age_group"] = pd.cut(data["age"], bins=bins, labels=labels)

data

   age  income age_group
0   18   20000     Young
1   22   25000     Adult
2   25   30000     Adult
3   30   40000     Adult
4   35   50000     Adult
5   40   60000     Adult
6   45   70000    Senior
7   50   80000    Senior
8   55   90000    Senior
9   60  100000    Senior


## **4. Equal Frequency Binning**
Each bin contains approximately the **same number of observations**.

In [4]:

data["income_bins"] = pd.qcut(data["income"], q=3)

data

   age  income age_group           income_bins
0   18   20000     Young  (19999.999, 40000.0]
1   22   25000     Adult  (19999.999, 40000.0]
2   25   30000     Adult  (19999.999, 40000.0]
3   30   40000     Adult    (40000.0, 70000.0]
4   35   50000     Adult    (40000.0, 70000.0]
5   40   60000     Adult    (40000.0, 70000.0]
6   45   70000    Senior   (70000.0, 100000.0]
7   50   80000    Senior   (70000.0, 100000.0]
8   55   90000    Senior   (70000.0, 100000.0]
9   60  100000    Senior   (70000.0, 100000.0]


# **Binarization**
Binarization converts numeric values into **0 or 1 based on a threshold**.


## **5. Binarization using sklearn**

In [5]:

binarizer = Binarizer(threshold=40)

age_array = data[["age"]]

binary_age = binarizer.fit_transform(age_array)

print(binary_age)

[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]]


# **Discretization**
Discretization converts continuous features into **discrete bins** using machine learning tools.


## **6. Discretization using KBinsDiscretizer**

In [6]:

kbins = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="uniform")

age_discretized = kbins.fit_transform(data[["age"]])

print(age_discretized)

[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]]

c:\Users\Pradhumn\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


## **7. Discretization with One-Hot Encoding**

In [7]:

kbins = KBinsDiscretizer(n_bins=3, encode="onehot-dense", strategy="uniform")

age_discretized = kbins.fit_transform(data[["age"]])

print(age_discretized)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]

c:\Users\Pradhumn\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


## **8. Different Discretization Strategies**

KBinsDiscretizer supports different strategies:

- **uniform** → equal width bins
- **quantile** → equal number of samples in each bin
- **kmeans** → bins created using clustering

In [8]:

kbins = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="quantile")

age_discretized = kbins.fit_transform(data[["age"]])

print(age_discretized)

[[0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [2.]
 [2.]
 [2.]]


## **9. When to Use These Techniques**

**Binning**
- Reduce noise in data
- Convert continuous variables into categories

**Binarization**
- Convert numeric features to binary indicators

**Discretization**
- Helpful for models that work better with categorical inputs